version: "3.3"
services:
  app:
    container_name: pass-interviews-app-container
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    networks:
      - app-network
      - rabbitmq_go_net
      
networks:
  app-network:
    driver: bridge
  rabbitmq_go_net:
    driver: bridge