version: "3.8"
services:
  app:
    container_name: app-container
    build:
      context: .
    restart: always
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    networks:
      - app-network
  
  app2:
    container_name: app2-container
    build:
      context: ../rabbitmq
    restart: always
    volumes:
      - ../rabbitmq/src:/app/src
    networks:
      - app-network

  nginx:
    container_name: nginx-container
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.prod.conf.template:/etc/nginx/templates/default.conf.template
    env_file:
      - ./.env
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge