version: "3.3"
services:
  app:
    image: omarhosny102/pass-interviews-app:v5.0
    container_name: pass-interviews-app-container
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge
