version: "3.3"
services:
  app:
    container_name: app-contianer
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge