openapi: 3.0.0

paths:
  /interviews/{_id}:
    put:
      summary: Update interview info
      description: Update the information of a specific interview.
      tags:
        - interviews
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: _id
          required: true
          schema:
            type: string
            pattern: '^[a-fA-F0-9]{24}$'
            format: objectid
            description: The ID of the interview
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InterviewUpdateRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Interview'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
  /interviews/{_id}/reviews:
    put:
      summary: Update interview review
      description: Update the review of a specific interview.
      tags:
        - interviews
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: _id
          required: true
          schema:
            type: string
            pattern: '^[a-fA-F0-9]{24}$'
            format: objectid
            description: The ID of the interview
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InterviewUpdateReviewRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Interview'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
  /interviews/{_id}/confirmation:
    put:
      summary: Confirm interview
      description: Confirm a specific interview.
      tags:
        - interviews
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: _id
          required: true
          schema:
            type: string
            pattern: '^[a-fA-F0-9]{24}$'
            format: objectid
            description: The ID of the interview
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Interview'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
  /interviews/{_id}/rejection:
    put:
      summary: Reject interview
      description: Reject a specific interview.
      tags:
        - interviews
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: _id
          required: true
          schema:
            type: string
            pattern: '^[a-fA-F0-9]{24}$'
            format: objectid
            description: The ID of the interview
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Interview'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'